# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 9007
  servlet:
    context-path: cApi
#http://localhost:9007/cApi/swagger-ui.html
swagger:
  basePackage: com.jinhe
  title: RESTful API 文档
  description:  RESTful API 文档
  version: 1.0.0-SNAPSHOT
# mysql
spring:
  resources:
    #当前启动目录下相对路径
    static-locations: file:./static/,file:./public/
  # 环境 dev|test|prod
  profiles:
    active: prod
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  application:
    name: springboot-jwt
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 106.13.102.215
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: Mas@12345
file:
  root:
    #存储路径
    path: "C:\\mydata\\generator\\version06\\"
config:
  jwt:
    # 加密密钥
    secret: abcdefg1234567
    # token有效时长
    expire: 3600
    # header 名称
    header: Authorization
    tokenStartWith: Bearer
#mybatis
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.jinhe.modules.*.entity
  configuration.jdbc-type-for-null: null
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  NONE:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID", AUTO: MP自动决定;
      id-type: UUID
      #字段策略 IGNORED:"忽略判断", NOT_NULL:"非 NULL 判断", NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      capital-mode: true
      #table-prefix: sys_
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
      # 数据库类型
      db-type: mysql
    #刷新mapper 调试神器
    refresh: true
    # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    # 打印sql日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level: info
  level.com.jinhe: info
com:
  gaoice:
    easyexcel:
      enable-excel-file: true
      enable-sheet-info: true
      enable-response-excel: true