# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-connections: 300
    max-http-form-post-size: 300
    accept-count: 300
    threads:
      max: 500
      min-spare: 20
  port: 8098
  servlet:
    context-path:
  max-http-header-size: 10240
version: '@project.version@'
#   context-path: /cApi
#http://localhost:8098/swagger-ui/
swagger:
  basePackage: com.jinhe
  title: RESTful API 文档
  description:  RESTful API 文档
  version: 1.0.0-SNAPSHOT
jinhe:
  #排除需要权限验证的模块
  filter: demo,download,allowApi,login
  #系统功能模块清单
  modules:
    demo: '演示测试模块'
    download: '自由下载模块'
    allowApi: '自由访问模块'
    login: '登录模块'
    system: '系统模块'
    sys: '业务相关的系统模块'
# mysql
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
  resources:
    #当前启动目录下相对路径
    static-locations: file:./static/,file:./public/
  # 环境 dev|test|prod
  profiles:
    active: prod
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  application:
    name: springboot-jwt
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 124.70.222.76
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: Mas@12345
file:
  root:
    #存储路径
    path: "C:\\mydata\\generator\\version06\\"
config:
  jwt:
    # 加密密钥
    secret: abcdefg1234567
    # token有效时长
    expire: 3600
    # header 名称
    header: Authorization
    tokenStartWith: Bearer
#mybatis
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.jinhe.modules.*.entity
  configuration.jdbc-type-for-null: null
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  NONE:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID", AUTO: MP自动决定;
      id-type: UUID
      #字段策略 IGNORED:"忽略判断", NOT_NULL:"非 NULL 判断", NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      capital-mode: true
      #table-prefix: sys_
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
      # 数据库类型
      db-type: mysql
    #刷新mapper 调试神器
    refresh: true
    # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    # 打印sql日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level: info
  level.com.jinhe: info
com:
  gaoice:
    easyexcel:
      enable-excel-file: true
      enable-sheet-info: true
      enable-response-excel: true
#http://localhost:8080/actuator
management:
  endpoints:
    web:
      exposure:
        include: ['metrics']
  endpoint:
    health:
      enabled: true
      show-details: always
    info:
      enabled: true
  health:
    redis:
      enabled: false
#  endpoint:
#    auditevents: # 1、显示当前引用程序的审计事件信息，默认开启
#      enabled: true
#      cache:
#        time-to-live: 10s # 配置端点缓存响应的时间
#    beans: # 2、显示一个应用中所有 Spring Beans 的完整列表，默认开启
#      enabled: true
#    conditions: # 3、显示配置类和自动配置类的状态及它们被应用和未被应用的原因，默认开启
#      enabled: true
#    configprops: # 4、显示一个所有@ConfigurationProperties的集合列表，默认开启
#      enabled: true
#    env: # 5、显示来自Spring的 ConfigurableEnvironment的属性，默认开启
#      enabled: true
#    flyway: # 6、显示数据库迁移路径，如果有的话，默认开启
#      enabled: true
#    health: # 7、显示健康信息，默认开启
#      enabled: true
#      show-details: always
#    info: # 8、显示任意的应用信息，默认开启
#      enabled: true
#    liquibase: # 9、展示任何Liquibase数据库迁移路径，如果有的话，默认开启
#      enabled: true
#    metrics: # 10、展示当前应用的metrics信息，默认开启
#      enabled: true
#    mappings: # 11、显示一个所有@RequestMapping路径的集合列表，默认开启
#      enabled: true
#    scheduledtasks: # 12、显示应用程序中的计划任务，默认开启
#      enabled: true
#    sessions: # 13、允许从Spring会话支持的会话存储中检索和删除(retrieval and deletion)用户会话。使用Spring Session对反应性Web应用程序的支持时不可用。默认开启。
#      enabled: true
#    shutdown: # 14、允许应用以优雅的方式关闭，默认关闭
#      enabled: true
#    threaddump: # 15、执行一个线程dump
#      enabled: true
#    # web 应用时可以使用以下端点
#    heapdump: # 16、    返回一个GZip压缩的hprof堆dump文件，默认开启
#      enabled: true
#    jolokia: # 17、通过HTTP暴露JMX beans（当Jolokia在类路径上时，WebFlux不可用），默认开启
#      enabled: true
#    logfile: # 18、返回日志文件内容（如果设置了logging.file或logging.path属性的话），支持使用HTTP Range头接收日志文件内容的部分信息，默认开启
#      enabled: true
#    prometheus: #19、以可以被Prometheus服务器抓取的格式显示metrics信息，默认开启
#      enabled: true